### ISSUE TITLE
Hi, any more dev on branch cm-13.0 or mkm?

### ISSUE THREAD

**Issue by imknown** [AlvaroBrey/android_device_tcl_q39#1]
also anyother released roms via your cm12.1 ?
: )

**Comment by AlvaroBrey** [comment]
I am not developing for mkm, and cm-13.0 is pretty difficult right now (need to update kernel). I might try to release something in the future but I can't promise anything.
My CM12.1 roms are released in this thread:
http://community.umidigi.com/forum.php?mod=viewthread&tid=2286&extra=page%3D1%26filter%3Dtypeid%26typeid%3D54
Cheers!

**Comment by imknown** [comment]
:laughing:  haha, thx, we will waiting for.

**Comment by imknown** [comment]
what about 'https://github.com/NX511J-dev' ? this is the phone repo of nubia Z9mini.

the are the hardware configurations are similar.. also they have CM13.0 builds. :+1: 

http://bbs.nubia.cn/forum.php?mod=forumdisplay&fid=600&filter=heat&orderby=heats

**Comment by AlvaroBrey** [comment]
There are plenty of similar devices to ours with cm13.0, but that only helps marginally. Z9 mini, as most of them, has kernel sources, something we don't.
My priority now is to get  12.1 sources clean and up to date. Once that's done I may try my luck in cm13. 
Please don't revive dead issues for these kind of things, that's what the forums are for. I appreciate you're trying to help, though.
