### ISSUE TITLE
tried to build, but failed, found no device

### ISSUE THREAD

**Issue by imknown** [AlvaroBrey/android_device_tcl_q39#4]
i used to compile cm12.1 with this device tree, but i can not found this device tag.

i have add `...\.repo\local_manifests\roomservice.xml` with:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote fetch="git://github.com/ontherunvaro" name="ontherunvaro" />
  <project name="ontherunvaro/android_device_tcl_q39" path="device/tcl/q39" remote="github" revision="cm-12.1"/>
</manifest>
```

and any guide for helping compile ? i just read CM, OMNI, SudaMod, Mokee's manual..

**Comment by AlvaroBrey** [comment]
[Here](http://wiki.cyanogenmod.org/w/Development)'s some useful resources

In my local_manifests folder I have:
tcl_q39.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project path="device/tcl/q39" name="ontherunvaro/android_device_tcl_q39" remote="github"  revision="cm-12.1"/>

  <project path="vendor/tcl" name="ontherunvaro/proprietary_vendor_tcl" remote="github" revision="cm-12.1" />

</manifest>
```

and qcom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project path="device/qcom/common" name="CyanogenMod/android_device_qcom_common" remote="github" revision="cm-12.1"/>
  <project path="hardware/qcom/fm" name="CyanogenMod/android_hardware_qcom_fm" remote="github" revision="cm-12.1"/>
  <project path="external/mm-dash" name="CyanogenMod/android_external_mm-dash" remote="github" revision="cm-12.1"/>
</manifest>
```

You shouldn't be using roomservice.xml, it's deprecated. You should define custom XMLs for your different devices or common sources (like qcom).

Anyway, issues are NOT the place to be asking for dev support. I am closing this one and please do not use issues for this again.
